# Site settings
title: bodgix blog
description: > # this means to ignore newlines until "baseurl:"
  Welcome to bodgix blog. A place for my ideas and notes.

  I'm a system engineer at Workday, I'm interested in Linux, monitoring,
  configuration management, Ruby, Perl, web and things like that.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bodgix.github.io" # the base hostname & protocol for your site
twitter_username: bodgix
github_username:  bodgix

# Build settings
markdown: kramdown
