# Site settings
title: bodgix blog
description: > # this means to ignore newlines until "baseurl:"
  Welcome to bodgix blog. A place for my ideas and notes.

  I'm currenlty a Software Engineer at Workday, working primarily in Ruby
  on a cloud infrastructure related project.

  I'm a former Systems Engineer and I'm also interested in all things Linux,
  monitoring, configuration management, Ruby, Perl, etc.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bodgix.github.io" # the base hostname & protocol for your site
twitter_username: bodgix
github_username:  bodgix
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
